# Generated by Django 2.2.3 on 2019-12-18 05:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20191218_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 5, 35, 23, 330055, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
