# Generated by Django 2.2.3 on 2019-12-18 05:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20191217_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 5, 28, 59, 420817, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
